services:
  postgres:
    image: postgres:16.3
    container_name: BankAppWDBK
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  mail-dev:
    container_name: MailDev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres_data:
    driver: local

